try:
    from deep_research_client._version import __version__, __version_tuple__
except ImportError:  # pragma: no cover
    __version__ = "0.0.0"
    __version_tuple__ = (0, 0, 0)

from .client import DeepResearchClient
from .models import ResearchResult, ProviderAttempt, ProviderConfig, CacheConfig, QueryMetadata, EditHistoryEntry, ProviderHealth
from .exceptions import (
    MAX_DETAIL_CHARS,
    MIN_DETAIL_CHARS,
    MAX_RESET_CHARS,
    truncate_detail,
    FALLBACK_WORTHY_ERRORS,
    is_fallback_worthy,
    ProviderError,
    ProviderAuthError,
    ProviderBillingError,
    ProviderQuotaError,
    ProviderNotConfiguredError,
    ProviderNotInstalledError,
    ProviderRateLimitError,
    ProviderTransientError,
    classify_status,
    classify_exception,
    extract_status_code,
)
from .processing import ResearchProcessor, TemplateProcessor, ResultFormatter
from .cache import extract_title_from_markdown, preprocess_markdown
from .model_cards import (
    ModelCard,
    ProviderModelCards,
    CostLevel,
    TimeEstimate,
    ModelCapability,
    get_provider_model_cards,
    list_all_models,
    find_models_by_cost,
    find_models_by_capability,
    resolve_model_alias,
    list_all_aliases
)
from .validation import (
    LabelAgreement,
    ReferenceCheck,
    ReferenceStatus,
    ReferenceValidationReport,
    ReferenceValidator,
    SupportingTextCheck,
    TermCheck,
    TermStatus,
    TermValidationReport,
    TermValidator,
    TopicalRelevance,
    extract_references,
    extract_terms,
    term_validator_is_available,
    validator_is_available,
)

__all__ = [
    "DeepResearchClient",
    "ResearchResult",
    "ProviderAttempt",
    "ProviderConfig",
    "CacheConfig",
    "QueryMetadata",
    "EditHistoryEntry",
    "ProviderHealth",
    "MAX_DETAIL_CHARS",
    "MIN_DETAIL_CHARS",
    "MAX_RESET_CHARS",
    "truncate_detail",
    "FALLBACK_WORTHY_ERRORS",
    "is_fallback_worthy",
    "ProviderError",
    "ProviderAuthError",
    "ProviderBillingError",
    "ProviderQuotaError",
    "ProviderNotConfiguredError",
    "ProviderNotInstalledError",
    "ProviderRateLimitError",
    "ProviderTransientError",
    "classify_status",
    "classify_exception",
    "extract_status_code",
    "ResearchProcessor",
    "TemplateProcessor",
    "ResultFormatter",
    "ModelCard",
    "ProviderModelCards",
    "CostLevel",
    "TimeEstimate",
    "ModelCapability",
    "get_provider_model_cards",
    "list_all_models",
    "find_models_by_cost",
    "find_models_by_capability",
    "resolve_model_alias",
    "list_all_aliases",
    "extract_title_from_markdown",
    "preprocess_markdown",
    "ReferenceCheck",
    "ReferenceStatus",
    "ReferenceValidationReport",
    "ReferenceValidator",
    "SupportingTextCheck",
    "TopicalRelevance",
    "extract_references",
    "validator_is_available",
    "LabelAgreement",
    "TermCheck",
    "TermStatus",
    "TermValidationReport",
    "TermValidator",
    "extract_terms",
    "term_validator_is_available",
]
